# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        # Core subpackage
        'core',
        'core.logger',
        'core.ws_manager',
        'core.settings_manager',
        'core.window_monitor',
        # Vision subpackage
        'vision',
        'vision.screen_parser',
        'vision.ui_detector',
        'vision.ocr_engine',
        'vision.a11y_reader',
        'vision.element_merger',
        # Task subpackage
        'task',
        'task.planner',
        'task.agent',
        'task.actuator',
        'task.context_manager',
        # LLM subpackage
        'task',
        'llm',
        'llm.llm_provider',
        'llm.openai_provider',
        'llm.gemini_provider',
        'llm.copilot_provider',
        'llm.orchestrator',
        # FastAPI / Uvicorn internals that PyInstaller misses
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        # Other dependencies often missed
        'multiprocessing',
        'pydantic',
        'pyautogui',
        'pyperclip',
        'PIL',
        'cv2',
        'numpy',
        'structlog',
        'keyring',
        'keyring.backends',
        'keyring.backends.Windows',
        'dotenv',
        'openai',
        'google.generativeai',
        'websockets',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'starlette',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'httptools',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'torch',
        'torchvision',
        'ultralytics',
        'transformers',
        'timm',
        'einops',
        'mkl',
        'intel-openmp',
        'paddle',
        'paddlepaddle',
        'paddleocr',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
